Repository EO2-WAVY/WavyBackend, pull requests merged in 2021-09, with the labels that each got.

#16 [#15] Tag 엔티티 추가
  src/app.module.ts
  src/ref-videoes/entities/ref-video.entity.ts
  src/ref-videoes/entities/tag.entity.ts
Labels: feat

#17 [#11] 학습용 동영상 API 구현
  src/analyses/entities/analyses.entity.ts
  src/app.module.ts
  src/common/dtos/output.dto.ts
  src/common/dtos/pagination.dto.ts
  src/common/entities/core.entity.ts
  src/common/enums/code.enum.ts
  src/members-ref-videoes/entities/members-ref-videoes.entity.ts
  src/practices/entities/practice.entity.ts
  src/ref-videoes/ref-videoes.module.ts
  src/ref-videos/dtos/ref-video.dto.ts
  src/ref-videos/dtos/ref-videos.dto.ts
  src/ref-videos/entities/ref-video.entity.ts
  src/ref-videos/entities/tag.entity.ts
  src/ref-videos/ref-videos.controller.ts
  src/ref-videos/ref-videos.module.ts
  src/ref-videos/ref-videos.service.ts
Labels: feat

#21 [#20] 학습용 동영상 조회 API에 tag 인자 적용
  package-lock.json
  package.json
  src/common/dtos/pagination.dto.ts
  src/ref-videos/dtos/ref-videos.dto.ts
  src/ref-videos/entities/ref-video.entity.ts
  src/ref-videos/entities/tag.entity.ts
  src/ref-videos/ref-videos.service.ts
Labels: feat

#10 [#3] mbr_exp_history 엔티티 추가
  src/app.module.ts
  src/common/enums/code.enum.ts
  src/members/entities/mbr-exp-history.entity.ts
  src/members/entities/members.entity.ts
Labels: feat

#29 [#25] 보관 API 개발
  package-lock.json
  src/app.module.ts
  src/bookmarks/bookmarks.controller.ts
  src/bookmarks/bookmarks.module.ts
  src/bookmarks/bookmarks.service.ts
  src/bookmarks/dtos/bookmarks.dto.ts
  src/bookmarks/dtos/create-bookmark.dto.ts
  src/bookmarks/dtos/delete-bookmark.dto.ts
  src/members-ref-videoes/entities/members-ref-videoes.entity.ts
  src/members-ref-videoes/members-ref-videoes.module.ts
  src/members/entities/members.entity.ts
  src/ref-videos/entities/ref-video.entity.ts
  src/ref-videos/ref-videos.service.ts
Labels: feat

#55 [#51] 회원 API Swagger 작성
  src/main.ts
  src/members/dtos/create-mbr-exp-history.ts
  src/members/dtos/get-mbr-exp-history.ts
  src/members/dtos/get-member.dto.ts
  src/members/dtos/get-statics.dto.ts
  src/members/entities/mbr-exp-history.entity.ts
  src/members/entities/members.entity.ts
  src/members/members.controller.ts
  src/members/members.service.ts
Labels: documentation

#56 [#52] 인증 Swagger 작성
  src/auth/auth-jwt.middleware.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.service.ts
  src/auth/dtos/get-kakak-login-url.dto.ts
  src/auth/dtos/get-token.dto.ts
  src/auth/dtos/kakao-redirect.dto.ts
  src/members/members.controller.ts
  src/members/members.service.ts
Labels: documentation

#64 [#58] 회원 탈퇴 후 재가입시 발생하는 버그 수정
  src/members/members.service.ts
Labels: bug
